title: Islands Corp Support
description: A hub for all things Islands
baseurl: "/"
url: "https://zimo-gu.github.io/islandscorpdocs/"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Group":
    - "https://web.roblox.com/groups/10952536/Flex-Hotels#!/about"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
