title: Islands Corp Support
description: A hub for all things Islands
baseurl: "/"
url: "https://zimo-gu.github.io/islandscorpdocs/"

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Group":
    - "https://www.roblox.com/groups/2700627/BloxStreet-Corporation#!/about"
  "Store":
    - "https://www.roblox.com/games/539960592/BloxStreet-Shopping"
  "Training Center":
    - "https://www.roblox.com/games/624472608/Training-Center"
  "Quiz Center":
    - "https://www.roblox.com/games/652098479/Quiz-Center"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
